version: '3.9'

volumes:
  redis-data:

services:
  redis:
    image: redis:latest
    container_name: "redis"
    env_file:
      - .env
    ports:
      - "${REDIS_PORT-6379}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - default